# Generated by Django 4.2.7 on 2023-11-19 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mis_Cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bandahoraria',
            options={'verbose_name': 'Banda Horaria', 'verbose_name_plural': 'Bandas Horarias'},
        ),
    ]
