# Generated by Django 4.2.7 on 2023-11-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mis_Cursos', '0002_alter_bandahoraria_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nota',
            field=models.IntegerField(default=0),
        ),
    ]
